domain: github.io
url: https://targz.github.io/
baseurl: "/targz.fr-2025"

title: Targz
email: contact@targz.fr
author: Targz

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
